spring:
  profiles:
    active: prod

#server:
#  port: 8080
#spring:
#  datasource:
#    password: 123456
#    username: root
#    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: user-manage
#mybatis:
#  type-aliases-package: com.hzmciu.usermanage.entity;
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

#  mapper-locations: classpath:mapping/*Mapper.xml

