server:
  port: 8080
spring:
  datasource:
    master:
      password: 123456
      username: root
      jdbc-url: jdbc:mysql://localhost:3309/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      password: 123456
      username: root
      jdbc-url: jdbc:mysql://localhost:3312/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-manage
mybatis:
  type-aliases-package: com.hzmciu.usermanage.entity;
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
