spring:
  datasource:
    master:
      password: 123456
      username: root
      jdbc-url: jdbc:mysql://localhost:3309/experiment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      password: 123456
      username: root
      jdbc-url: jdbc:mysql://localhost:3312/experiment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: experiment-manage
mybatis:
  type-aliases-package: com.hzmciu.experimentmanage.entity
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888